name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Show repo structure
        run: ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          echo "Installing dependencies from requirements.txt..."
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          echo "Running migrations..."
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          echo "Running tests..."
          python manage.py test
